### ISSUE TITLE
Rive Renderer renders transparent animations incorrectly.

### ISSUE THREAD

**Issue by OlegBezr** [rive-app/rive-ios#299] opened 2024-04-05 21:55 UTC
### Description
Rive Renderer renders transparent animations incorrectly.

### Provide a Repro
minimal iOS SwiftUI app demonstrating the issue:
https://github.com/OlegBezr/RiveTransparentBug

#### Source `.riv`/`.rev` file
[RiveRenderer_transparency_bug.zip](https://github.com/rive-app/rive-ios/files/14891064/RiveRenderer_transparency_bug.zip)

### Expected behavior
The animation should look the same as in Skia. With RiveRenderer there's a dark gray color in place of transparent color.

#### Screenshots
Skia (expected animation)

https://github.com/rive-app/rive-ios/assets/47900108/d1fd9ff8-5263-4e07-9c2e-1517a44f4292

Rive Renderer (bug)

https://github.com/rive-app/rive-ios/assets/47900108/f9507ab7-2131-46be-ac87-b41725a74234

### Device & Versions (please complete the following information)
- Devices tested: physical iPhone 14 Pro Max, simulator iPhone SE 2020
- iOS versions: 17.3.1, 17.2

#### Additional context
Bug first mentioned here: 
https://github.com/rive-app/rive-ios/issues/269#issuecomment-2035371485

**Comment by OlegBezr** [comment] 2024-04-15 18:38
@HayesGordon, looking forward to your feedback on this. Please let me know if you need anything else to make the bug clear

**Comment by OlegBezr** [comment] 2024-05-15 22:41
@HayesGordon, we are still experiencing issues with first app launch animation loading using Skia. Really want to switch to RiveRenderer but this issue blocks us. Please let me know if there are any updates regarding this issue or any way we could contribute more to speed up the resolution. Appreciate your work, thank you!

**Comment by HayesGordon** [comment] 2024-06-11 12:49
Hi @OlegBezr, I'll escalate this with the rest of the team. Thanks for following up.

**Comment by simontreny** [comment] 2024-06-24 12:20
I encounter the same issue as well (see the dark edges on the cloud on top).

I think this is related to premultiplied alpha in texture assets as it only affects bitmaps and not vectorial graphics, and only with Rive's own renderer.

<img width="505" alt="Rive renderer glitch" src="https://github.com/rive-app/rive-ios/assets/20420653/7e4c41db-2df2-4c73-bbff-61a77d613cb9">

**Comment by neon8bit** [comment] 2024-11-28 16:15
@HayesGordon hi! Are there any new on this one?
Unfortunately, we cannot upgrade to any rive version higher than 5.16.0 because of this issue

**Comment by HayesGordon** [comment] 2024-11-28 16:54
This issue should be resolved. That is our mistake for not closing this.

I'll go ahead and close this issue, but if anyone sees anything different please reopen and if you can provide a .riv file that reproduces that will be a big help.

**Closed by HayesGordon** 2024-11-28 16:54 UTC

**Comment by HayesGordon** [comment] 2024-11-28 16:58
As an extra note, since this issue was opened the Rive Editor has been updated to also use the Rive Renderer.

Whatever you see in the Editor should look the same at runtime (if you're using the Rive Renderer). Please open an issue if that is not the case.
